CREATE TABLE IF NOT EXISTS computers (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  serialNumber VARCHAR(255) NOT NULL,
  serialOverride VARCHAR(255) NULL,
  manufacturer VARCHAR(255) NULL,
  model VARCHAR(255) NULL,
  operatingSystem VARCHAR(255) NULL,
  processor TEXT NULL,
  storage TEXT NULL,
  memory VARCHAR(255) NULL,
  gpu TEXT NULL,
  macAddress VARCHAR(255) NULL,
  details TEXT NULL,
  hostname VARCHAR(255) NULL,
  username VARCHAR(255) NULL,
  machineType VARCHAR(100) NOT NULL,
  acquiredOn DATE NULL,
  office VARCHAR(255) NOT NULL,
  parHolder VARCHAR(255) NULL,
  primaryUser VARCHAR(255) NULL,
  remarks TEXT NULL,
  collectedOn DATETIME(3) NOT NULL,
  scriptVersion VARCHAR(100) NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_computers_serial_number (serialNumber),
  KEY idx_computers_hostname (hostname),
  KEY idx_computers_office (office)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS peripherals (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  syncId VARCHAR(64) NOT NULL,
  computerId BIGINT UNSIGNED NULL,
  type VARCHAR(255) NOT NULL,
  manufacturer VARCHAR(255) NULL,
  model VARCHAR(255) NULL,
  serialNumber VARCHAR(255) NULL,
  assetTag VARCHAR(255) NULL,
  assignedUser VARCHAR(255) NULL,
  remarks TEXT NULL,
  deletedAt DATETIME(3) NULL,
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_peripherals_sync_id (syncId),
  KEY idx_peripherals_computer (computerId),
  CONSTRAINT fk_peripherals_computer FOREIGN KEY (computerId) REFERENCES computers(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
